name: Container image scan
on: pull_request
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: aquasecurity/trivy-action@v0.19.0
        with:
          image-ref: nginx:1.11.0
          severity: CRITICAL, HIGH
          exit-code: 1
