name: Fail-fast matrix
on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        time: [10, 20, 30]
    steps:
      - run: sleep "${SLEEP_TIME}" && exit 1
        env:
          SLEEP_TIME: ${{ matrix.time }}
