name: Prevent security misconfigurations
on: pull_request
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: config
          severity: CRITICAL, HIGH
          exit-code: 1
